spring:
  config:
    import:
      - optional:classpath:/application-gitlab.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8888