spring:
  config:
    import:
      - optional:classpath:/application-gitlab.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
server:
  port: 8888
logging:
  level:
    root: "info"
    com.swlab.gitlab.web: "debug"