spring:
  config:
    import:
      - optional:classpath:/application-gitlab.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
server:
  port: 8888
logging:
  level:
    root: "info"
    com.swlab.gitlab.web: "debug"
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**